version: '3.5'
services:
  apache:
    container_name: truss_apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - 80:80
  mysql:
    container_name: truss_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./.env
  phpmyadmin:
    container_name: truss_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env
  gitserver:
    container_name: truss_gitserver
    build:
      context: ./gitserver
      dockerfile: Dockerfile
    ports:
      - 22:22
