version: '3.4'
services:
  backend:
    container_name: truss_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend/app:/var/www/symfony"
      - "./backend/keys:/git/keys"
      - "./backend/repos:/git/repos"
    ports:
      - "22:22"
      - "80:80"
    links:
      - "mysql:mysql"
  mysql:
    container_name: truss_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    env_file:
      - ".env"
  phpmyadmin:
    container_name: truss_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - "mysql:mysql"
    env_file:
      - ".env"