version: '3.5'
services:
  backend:
    container_name: truss_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
      - ./backend/.ssh:/home/git/.ssh
      - ./backend/repos:/home/git/repos
      - ./backend/git-shell-commands:/home/git/git-shell-commands
    ports:
      - "80:80"
      - "22:22"
  mysql:
    container_name: truss_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./.env
  phpmyadmin:
    container_name: truss_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./.env
  testserver:
    container_name: truss_testserver
    build:
      context: ./testserver
      dockerfile: Dockerfile
