version: '3.4'
services:
  backend:
    container_name: truss_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend/app:/var/www/"
    ports:
      - "80:80"
    links:
      - "mysql:mysql"
  mysql:
    container_name: truss_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    env_file:
          - ".env"
  phpmyadmin:
    container_name: truss_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - "mysql:mysql"
    env_file:
          - ".env"
  git:
    container_name: truss_git
    build:
      context: ./git
      dockerfile: Dockerfile
    ports:
      - "22:22"
    volumes:
      - "./git/keys:/git-server/keys"
      - "./git/repos:/git-server/repos"