version: '3.5'
services:
  apache:
    container_name: lens_apache
    build:
      context: ./apache
      dockerfile: Dockerfile
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - 80:80
  mysql:
    container_name: lens_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./.env
  phpmyadmin:
    container_name: lens_phpmyadmin
    build:
      context: ./phpmyadmin
      dockerfile: Dockerfile
    ports:
      - 8080:80
    env_file:
      - ./.env
